version: 2.1
jobs:
  build:
    working_directory:  ~/sync-endpoint
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - setup_remote_docker

      - run: sudo apt-get update && sudo apt-get install -y maven

      - run:
          name: clean
          command: mvn clean

      - run: docker swarm init

      - run: mvn clean install -Dmaven.test.skip -DskipTests


      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  unit-test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/sync-endpoint
    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: running unit tests
          command: mvn surefire:test


      - store_test_results:
          path: /tmp/test-results




  integration-test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/sync-endpoint
    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: running integration tests
          command: mvn failsafe:integration-test

      - store_test_results:
          path:  /tmp/test-results



workflows:
  build:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - build

