version: 2.1
jobs:
  build:
    working_directory:  ~/sync-endpoint
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - setup_remote_docker

      - run: sudo apt-get update && sudo apt-get install -y maven

      - run:
          name: clean
          command: mvn clean

      - run: mvn clean install -Dmaven.test.skip -DskipTests

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-


      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: my-service/target/my-service.jar

  unit-test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/sync-endpoint
    steps:
      - checkout

      - setup_remote_docker
      - run:
          name: clean
          command: mvn clean
      - run:
          name: unit-test
          command: |
            mvn package
            mvn clean test -DskipTests=false -DskipITs=true          


  integration test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/sync-endpoint
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: clean
          command: mvn clean
      - run:
          name: Running integration test
          command: |
            mvn clean verify -DskipTests=true -DskipITs=false          


workflows:
  build:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration test:
          requires:
            - unit-test


