version: 2.1
jobs:
  build:
    working_directory:  ~/sync-endpoint
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - setup_remote_docker

      - run: sudo apt-get update && sudo apt-get install -y maven

      - run:
          name: clean
          command: mvn clean

      - run: mvn clean install

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-


      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: my-service/target/my-service.jar



workflows:
  build:
    jobs:
      - build



