version: 2.1
jobs:
  build and unit test:
    working_directory:  ~/sync-endpoint
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      # This gets the local Docker service started
      - setup_remote_docker
      - run:
          name: Install Docker CLI
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker $USER

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:  sudo apt-get update && sudo apt-get install -y maven
      - run:
          name: build and test
          command: |
            mvn clean install

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: my-service/target/my-service.jar


workflows:
  build:
    jobs:
      - build and unit test

